services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\DatabaseService:
        arguments:
            $dsn: '%env(resolve:DATABASE_DSN)%'
            $user: '%env(resolve:DATABASE_USER)%'
            $password: '%env(resolve:DATABASE_PASSWORD)%'
